server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file://C:\MSA_study_Git\Work\git-local-repo
          uri: https://github.com/hariBoWoo/tmax-Final-config
          default-label: main
  #          uri: file://C:\Users\Admin\Desktop\jieun\tmax\tmax_cloud\git-local-repo
  #          username: park940313@naver.com
  #          password: [password]
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest


management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh, refresh, metrics, beans, httptrace