server:
  port: 50001
#  address: 127.0.0.1

spring:
  application:
    name: user-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:mariadb://database-1.c4rcauqgpkcf.ap-northeast-3.rds.amazonaws.com:3306/tmax
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: rnjswlsgml!
  jpa:
    hibernate:
      ddl-auto: update
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: true
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tmaxFinal@gmail.com
    password: fjxnyscaqrtuvztb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  profiles:
#    include: oauth

#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome to the simple E-commerce.

#token:
#  expiration_time: 86400000
#  secret: user_token
#secret은 토큰을 생성할 때 어떤 키를 가지고 생성할것인지 지정
management:
  endpoints:
    web:
      exposure:
        include: info,refresh,health,beans,busrefresh

logging:
  level:
    com.example.userservice.client: DEBUG

