
server:
  port: 50002

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
#      database-platform: org.hibernate.dialect.MariaDB103Dialect
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/mydb
#    username: root
#    password: root1234
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:testdb
    #    username: sa
    #    password:
    generate-ddl: true
    show-sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, info, busrefresh
        
logging:
  level:
    com.example.orderservice: DEBUG

msg:
  kafkaip: 172.18.0.101:9092