server:
  port: 50002

spring:
  application:
    name: hr-service
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: true
    generate-ddl: true

  datasource:
    url: jdbc:mariadb://database-1.c4rcauqgpkcf.ap-northeast-3.rds.amazonaws.com:3306/tmax
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: rnjswlsgml!

  mail:
    host: smtp.gmail.com
    port: 587
    username: tmaxFinal@gmail.com
    password: fjxnyscaqrtuvztb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  profiles:
    include: oauth


#  jpa:
#    hibernate:
#      ddl-auto: update
#    h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#    generate-ddl: true
#    show-sql: true

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest


#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, info, busrefresh

logging:
  level:
    com.example.hrservice.client: DEBUG


#token:
#  expiration_time: 86400000
#  secret: user_token

  #token:
#  expiration_time: 864000000
#  secret: user_token
#gateway:
#  ip: 127.0.0.1
#
#token:
#  expiration_time: 864000000
#  secret: '{cipher}AQBSTibIkDoa4vgGNtMfiTI660f+Uj7m2gDVPCG+rH13VFlnpWmEmnoZtK9Ih3NHYr3yJZuo6PCENNuwP2+oAAC2uMwnO/NPzq0HRbOMIkAY570w9x0ZS7NMiRAKJ4u3l6cSI2dAXzYhWSbBcVEiIrMdlL5kuL8ZOXUIAcheEkaKiWk1UTAEH3+russ6yvSHjqBKbW1y1Ofd085X/9wdccT++WnkCu3i4B5zy2MiGKFAWAXdKlQB+yKPqvwKH69tGSTehH1ZJ7/xaUCS2poWbDHrgVXM4SiHhdkQejAZY9Ai+boQgu5VuDUY3jl/kW9H2L0Gl5oBTjNQ43QfquRnnAjdNcWui2IP8OgueKS79yGH5gzhxHnV/gYdFPpn11jhAFA29lr97PAjXzEvZY2ywnhm'

  #spring.mail.properties.mail.smtp.timeout=5000
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true
  packages-to-scan: com.example.hrservice.controller

